name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: wolf0110
          password: ${{ secrets.DOCKERTOKEN }}
      - uses: actions/checkout@v3	
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: wolf0110/website:latest
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.MS_WEBHOOK }}
        message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."
